name: Crystal CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v3

      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: latest

      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
