name: Crystal CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          apt update
          apt install -y g++ libsfml-dev

      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
