name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: get-cmake
      uses: lukka/get-cmake@v3.23.0

    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
